import type { Bank, PaymentMethod, Screenshot } from "./types";

export const SOCIAL_LINKS = {
	github: "https://github.com/mosabsomaer/Khazna",
	figma: "https://www.figma.com/design/eREKtHmHAHgfZIWI3kSjxP/Khazna",
	email: "mailto:mosabsomaer@gmail.com",
};

export const BANKS: Bank[] = [
	{
		id: "sahara-bank",
		name: "Sahara Bank",
		logoUrl: "/logos/banks/sahara-bank.svg",
		logomarkUrl: "/logos/bank-icons/sahara-bank.svg",
		colors: ["#002C4B", "#A77B18"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "yaqeen-bank",
		name: "Yaqeen Bank",
		logoUrl: "/logos/banks/yaqeen-bank.svg",
		logomarkUrl: "/logos/bank-icons/yaqeen-bank.svg",
		colors: ["#0B1338", "#F47D3F"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "north-bank",
		name: "North Africa Bank",
		logoUrl: "/logos/banks/north-bank.svg",
		logomarkUrl: "/logos/bank-icons/north-bank.svg",
		colors: ["#0055B8", "#E87200"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "bcd-bank",
		name: "Bank of Commerce & Development",
		logoUrl: "/logos/banks/bcd-bank.svg",
		logomarkUrl: "/logos/bank-icons/bcd-bank.svg",
		colors: ["#007F3E", "#FFC80F"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "atib-bank",
		name: "ATIB Bank",
		logoUrl: "/logos/banks/atib-bank.svg",
		logomarkUrl: "/logos/bank-icons/atib-bank.svg",
		colors: ["#E30E2D"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "investment-bank",
		name: "Arab Investment Islamic Bank",
		logoUrl: "/logos/banks/investment-bank.svg",
		logomarkUrl: "/logos/bank-icons/investment-bank.svg",
		colors: ["#DE4148", "#E6DAC8"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "islamic-bank",
		name: "Libyan Islamic Bank",
		logoUrl: "/logos/banks/islamic-bank.svg",
		logomarkUrl: "/logos/bank-icons/islamic-bank.svg",
		colors: ["#735D46", "#897852"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "tadamun-bank",
		name: "Tadamun Bank",
		logoUrl: "/logos/banks/tadamun-bank.svg",
		logomarkUrl: "/logos/bank-icons/tadamun-bank.svg",
		colors: ["#155957", "#21B5E9", "#B5D339"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "united-bank",
		name: "United Bank",
		logoUrl: "/logos/banks/united-bank.svg",
		logomarkUrl: "/logos/bank-icons/united-bank.svg",
		colors: ["#304365"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "al-seraj-islamic-bank",
		name: "Al Seraj Islamic Bank",
		logoUrl: "/logos/banks/al-seraj-islamic-bank.svg",
		logomarkUrl: "/logos/bank-icons/al-seraj-islamic-bank.svg",
		colors: ["#6E58A5"],
		hasScreenshots: false,

		type: "bank",
	},
	{
		id: "aman-bank",
		name: "Aman Bank",
		logoUrl: "/logos/banks/aman-bank.svg",
		colors: ["#102440", "#2C386B"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "andalus-bank",
		name: "Andalus Bank",
		logoUrl: "/logos/banks/andalus-bank.svg",
		logomarkUrl: "/logos/bank-icons/andalus-bank.svg",
		colors: ["#8C7032", "#BEA460"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "cbl-bank",
		name: "Central Bank of Libya",
		logoUrl: "/logos/banks/cbl-bank.svg",
		colors: ["#211E1F"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "fglb-bank",
		name: "First Gulf Libyan Bank",
		logoUrl: "/logos/banks/fglb-bank.svg",
		colors: ["#23387B", "#E62C27"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "imaar-bank",
		name: "Imaar Bank",
		logoUrl: "/logos/banks/imaar-bank.svg",
		logomarkUrl: "/logos/bank-icons/imaar-bank.svg",
		colors: ["#FA62FB", "#83C8FB"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "jumhouria-bank",
		name: "Jumhouria Bank",
		logoUrl: "/logos/banks/jumhouria-bank.svg",
		logomarkUrl: "/logos/bank-icons/jumhouria-bank.svg",
		colors: ["#002244"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "libyan-foreign-bank",
		name: "Libyan Foreign Bank",
		logoUrl: "/logos/banks/libyan-foreign-bank.svg",
		logomarkUrl: "/logos/bank-icons/libyan-foreign-bank.svg",
		colors: ["#051C2C"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "mediterranean-bank",
		name: "Mediterranean Bank",
		logoUrl: "/logos/banks/mediterranean-bank.svg",
		logomarkUrl: "/logos/bank-icons/mediterranean-bank.svg",
		colors: ["#1A61AE"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "national-commercial-bank",
		name: "National Commercial Bank",
		logoUrl: "/logos/banks/national-commercial-bank.svg",
		logomarkUrl: "/logos/bank-icons/national-commercial-bank.svg",
		colors: ["#0D4155", "#067937"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "nuran-bank",
		name: "Nuran Bank",
		logoUrl: "/logos/banks/nuran-bank.svg",
		logomarkUrl: "/logos/bank-icons/nuran-bank.svg",
		colors: ["#0093B4", "#81CCD6"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "wahda-bank",
		name: "Wahda Bank",
		logoUrl: "/logos/banks/wahda-bank.svg",
		logomarkUrl: "/logos/bank-icons/wahda-bank.svg",
		colors: ["#034694", "#27AAE2"],
		hasScreenshots: true,
		type: "bank",
	},
];

export const PAYMENT_METHODS: PaymentMethod[] = [
	{
		id: "sadad",
		name: "Sadad",
		logoUrl: "/logos/payment-methods/sadad.svg",
		colors: ["#67696B"],
		type: "payment_method",
	},
	{
		id: "edfa3li",
		name: "Edfa3li",
		logoUrl: "/logos/payment-methods/edfa3li.svg",
		colors: ["#0E2316", "#FEE600"],
		type: "payment_method",
	},
	{
		id: "mobicash",
		name: "MobiCash",
		logoUrl: "/logos/payment-methods/mobicash.svg",
		colors: ["#217FBE", "#219387"],
		type: "payment_method",
	},
	{
		id: "masrafy-pay",
		name: "Masrafy Pay",
		logoUrl: "/logos/payment-methods/masrafy-pay.svg",
		colors: ["#1A60AB", "#39BDEE"],
		type: "payment_method",
	},
	{
		id: "masrafy-plus",
		name: "Masrafy Plus",
		logoUrl: "/logos/payment-methods/masrafy-plus.svg",
		colors: ["#1A60AB", "#264594"],
		type: "payment_method",
	},
	{
		id: "ly-pay",
		name: "LY Pay",
		logoUrl: "/logos/payment-methods/ly-pay.svg",
		colors: ["#17A3DD", "#4EB3A7"],
		type: "payment_method",
	},
	{
		id: "al-seraj-pay",
		name: "Al Seraj Pay",
		logoUrl: "/logos/payment-methods/al-seraj-pay.svg",
		colors: ["#1F1F4E", "#6C56A2"],
		type: "payment_method",
	},
	{
		id: "nab4pay",
		name: "NAB4Pay",
		logoUrl: "/logos/payment-methods/nab4pay.svg",
		colors: ["#2D84C6", "#F59F1C"],
		type: "payment_method",
	},
	{
		id: "onepay",
		name: "OnePay",
		logoUrl: "/logos/payment-methods/onepay.svg",
		colors: ["#026795", "#49C4EA"],
		type: "payment_method",
	},
	{
		id: "sahara-pay",
		name: "Sahara Pay",
		logoUrl: "/logos/payment-methods/sahara-pay.svg",
		colors: ["#162C49", "#AA7E1A"],
		type: "payment_method",
	},
	{
		id: "yussor-pay",
		name: "Yussor Pay",
		logoUrl: "/logos/payment-methods/yussor-pay.svg",
		colors: ["#013E50", "#057A40"],
		type: "payment_method",
	},
	{
		id: "gpay",
		name: "GPay",
		logoUrl: "/logos/payment-methods/gpay.svg",
		colors: ["#0D74B8", "#010101"],
		type: "payment_method",
	},
	{
		id: "numo-pay",
		name: "Numo Pay",
		logoUrl: "/logos/payment-methods/numo-pay.svg",
		logomarkUrl: "/logos/payment-methods/numo-pay-icon.svg",
		colors: ["#404041", "#FFE000"],
		type: "payment_method",
	},
];

export const MOCK_SCREENSHOTS: Record<string, Screenshot[]> = {
	"sahara-bank": [
		{ id: "s1",  url: "/screenshots/sahara-bank/splash.png",                 label: "Splash Screen",        category: "onboarding" },
		{ id: "s2",  url: "/screenshots/sahara-bank/my-account.png",             label: "My Account",           category: "dashboard" },
		{ id: "s3",  url: "/screenshots/sahara-bank/main-menu.png",              label: "Main Menu",            category: "dashboard" },
		{ id: "s4",  url: "/screenshots/sahara-bank/menu.png",                   label: "Menu",                 category: "dashboard" },
		{ id: "s5",  url: "/screenshots/sahara-bank/financial-operations.png",   label: "Financial Operations", category: "transaction" },
		{ id: "s6",  url: "/screenshots/sahara-bank/financial-operations-2.png", label: "Financial Operations", category: "transaction" },
		{ id: "s7",  url: "/screenshots/sahara-bank/account-statement.png",      label: "Account Statement",    category: "dashboard" },
		{ id: "s8",  url: "/screenshots/sahara-bank/money-transfer.png",         label: "Money Transfer",       category: "transaction" },
		{ id: "s9",  url: "/screenshots/sahara-bank/qr-payment.png",             label: "QR Payment",           category: "transaction" },
		{ id: "s10", url: "/screenshots/sahara-bank/qr-payment-2.png",           label: "QR Payment",           category: "transaction" },
		{ id: "s11", url: "/screenshots/sahara-bank/qr-payment-3.png",           label: "QR Payment",           category: "transaction" },
		{ id: "s12", url: "/screenshots/sahara-bank/buy-prepaid-cards.png",      label: "Buy Prepaid Cards",    category: "transaction" },
		{ id: "s13", url: "/screenshots/sahara-bank/prepaid-card.png",           label: "Prepaid Card",         category: "dashboard" },
		{ id: "s14", url: "/screenshots/sahara-bank/cash-withdrawal.png",        label: "Cash Withdrawal",      category: "transaction" },
		{ id: "s15", url: "/screenshots/sahara-bank/lypay-payment.png",          label: "LYPAY Payment",        category: "transaction" },
		{ id: "s16", url: "/screenshots/sahara-bank/lypay-payment-2.png",        label: "LYPAY Payment",        category: "transaction" },
		{ id: "s17", url: "/screenshots/sahara-bank/onepay-payment.png",         label: "OnePay Payment",       category: "transaction" },
		{ id: "s18", url: "/screenshots/sahara-bank/onepay-transfer.png",        label: "OnePay Transfer",      category: "transaction" },
		{ id: "s19", url: "/screenshots/sahara-bank/financial-disclosure.png",   label: "Financial Disclosure", category: "dashboard" },
		{ id: "s20", url: "/screenshots/sahara-bank/transaction-password.png",   label: "Transaction Password", category: "auth" },
	],
	"north-bank": [
		{ id: "n1",  url: "/screenshots/north-bank/home.png",                    label: "Home",                  category: "dashboard" },
		{ id: "n2",  url: "/screenshots/north-bank/my-account.png",              label: "My Account",            category: "dashboard" },
		{ id: "n3",  url: "/screenshots/north-bank/account-statement.png",       label: "Account Statement",     category: "dashboard" },
		{ id: "n4",  url: "/screenshots/north-bank/cards.png",                   label: "Cards",                 category: "dashboard" },
		{ id: "n5",  url: "/screenshots/north-bank/cards-2.png",                 label: "Cards",                 category: "dashboard" },
		{ id: "n6",  url: "/screenshots/north-bank/cards-3.png",                 label: "Cards",                 category: "dashboard" },
		{ id: "n7",  url: "/screenshots/north-bank/cards-4.png",                 label: "Cards",                 category: "dashboard" },
		{ id: "n8",  url: "/screenshots/north-bank/cards-5.png",                 label: "Cards",                 category: "dashboard" },
		{ id: "n9",  url: "/screenshots/north-bank/basic-services.png",          label: "Basic Services",        category: "dashboard" },
		{ id: "n10", url: "/screenshots/north-bank/card-terms.png",              label: "Card Terms",            category: "onboarding" },
		{ id: "n11", url: "/screenshots/north-bank/card-terms-2.png",            label: "Card Terms",            category: "onboarding" },
		{ id: "n12", url: "/screenshots/north-bank/card-terms-3.png",            label: "Card Terms",            category: "onboarding" },
		{ id: "n13", url: "/screenshots/north-bank/card-terms-4.png",            label: "Card Terms",            category: "onboarding" },
		{ id: "n14", url: "/screenshots/north-bank/card-terms-5.png",            label: "Card Terms",            category: "onboarding" },
		{ id: "n15", url: "/screenshots/north-bank/card-terms-6.png",            label: "Card Terms",            category: "onboarding" },
		{ id: "n16", url: "/screenshots/north-bank/dont-count.png",              label: "Don't Count It",        category: "dashboard" },
		{ id: "n17", url: "/screenshots/north-bank/e-wallets.png",               label: "Electronic Wallets",    category: "dashboard" },
		{ id: "n18", url: "/screenshots/north-bank/financial-obligations.png",   label: "Financial Obligations", category: "dashboard" },
		{ id: "n19", url: "/screenshots/north-bank/insurance.png",               label: "Insurance",             category: "dashboard" },
		{ id: "n20", url: "/screenshots/north-bank/money-transfer.png",          label: "Money Transfer",        category: "transaction" },
		{ id: "n21", url: "/screenshots/north-bank/money-transfer-2.png",        label: "Money Transfer",        category: "transaction" },
		{ id: "n22", url: "/screenshots/north-bank/payments.png",                label: "Payments",              category: "transaction" },
	],
	"atib-bank": [
		{ id: "a1", url: "/screenshots/atib-bank/login.png",          label: "Login",         category: "auth" },
		{ id: "a2", url: "/screenshots/atib-bank/date-of-birth.png",  label: "Date of Birth", category: "onboarding" },
		{ id: "a3", url: "/screenshots/atib-bank/my-account.png",     label: "My Account",    category: "dashboard" },
		{ id: "a4", url: "/screenshots/atib-bank/menu.png",           label: "Menu",          category: "dashboard" },
		{ id: "a5", url: "/screenshots/atib-bank/settings.png",       label: "Settings",      category: "settings" },
		{ id: "a6", url: "/screenshots/atib-bank/conversion.png",     label: "Conversion",    category: "transaction" },
		{ id: "a7", url: "/screenshots/atib-bank/buy-cards.png",      label: "Buy Cards",     category: "transaction" },
	],
	"bcd-bank": [
		{ id: "b1", url: "/screenshots/bcd-bank/login.png",           label: "Login",         category: "auth" },
		{ id: "b2", url: "/screenshots/bcd-bank/onboarding.png",      label: "Onboarding",    category: "onboarding" },
		{ id: "b3", url: "/screenshots/bcd-bank/home.png",            label: "Home",          category: "dashboard" },
		{ id: "b4", url: "/screenshots/bcd-bank/my-cards.png",        label: "My Cards",      category: "dashboard" },
		{ id: "b5", url: "/screenshots/bcd-bank/transfer-list.png",   label: "Transfer List", category: "transaction" },
		{ id: "b6", url: "/screenshots/bcd-bank/buy-cards.png",       label: "Buy Cards",     category: "transaction" },
		{ id: "b7", url: "/screenshots/bcd-bank/branches.png",        label: "Branches",      category: "dashboard" },
		{ id: "b8", url: "/screenshots/bcd-bank/more.png",            label: "More",          category: "dashboard" },
		{ id: "b9", url: "/screenshots/bcd-bank/check.png",           label: "Check",         category: "transaction" },
	],
	"andalus-bank": [
		{ id: "and1",  url: "/screenshots/andalus-bank/home.png",          label: "Home",          category: "dashboard" },
		{ id: "and2",  url: "/screenshots/andalus-bank/accounts.png",      label: "Accounts",      category: "dashboard" },
		{ id: "and3",  url: "/screenshots/andalus-bank/cards.png",         label: "Cards",         category: "dashboard" },
		{ id: "and4",  url: "/screenshots/andalus-bank/card-store.png",    label: "Card Store",    category: "transaction" },
		{ id: "and5",  url: "/screenshots/andalus-bank/taysir-card.png",   label: "Taysir Card",   category: "dashboard" },
		{ id: "and6",  url: "/screenshots/andalus-bank/branches-atm.png",  label: "Branches & ATM",category: "dashboard" },
		{ id: "and7",  url: "/screenshots/andalus-bank/qr.png",            label: "QR",            category: "transaction" },
		{ id: "and8",  url: "/screenshots/andalus-bank/settings.png",      label: "Settings",      category: "settings" },
		{ id: "and9",  url: "/screenshots/andalus-bank/ld-account.png",    label: "LYD Account",   category: "dashboard" },
		{ id: "and10", url: "/screenshots/andalus-bank/transfer.png",      label: "Transfer",      category: "transaction" },
	],
	"jumhouria-bank": [
		{ id: "j1",  url: "/screenshots/jumhouria-bank/login.png",                 label: "Login",                category: "auth" },
		{ id: "j2",  url: "/screenshots/jumhouria-bank/visitor-area.png",          label: "Visitor Area",         category: "onboarding" },
		{ id: "j3",  url: "/screenshots/jumhouria-bank/accounts.png",              label: "Accounts",             category: "dashboard" },
		{ id: "j4",  url: "/screenshots/jumhouria-bank/current-account.png",       label: "Current Account",      category: "dashboard" },
		{ id: "j5",  url: "/screenshots/jumhouria-bank/current-account-2.png",     label: "Current Account",      category: "dashboard" },
		{ id: "j6",  url: "/screenshots/jumhouria-bank/current-account-3.png",     label: "Current Account",      category: "dashboard" },
		{ id: "j7",  url: "/screenshots/jumhouria-bank/financial-operations.png",  label: "Financial Operations", category: "transaction" },
		{ id: "j8",  url: "/screenshots/jumhouria-bank/payment.png",               label: "Payment",              category: "transaction" },
		{ id: "j9",  url: "/screenshots/jumhouria-bank/prepaid-cards.png",         label: "Prepaid Cards",        category: "dashboard" },
		{ id: "j10", url: "/screenshots/jumhouria-bank/settings.png",              label: "Settings",             category: "settings" },
		{ id: "j11", url: "/screenshots/jumhouria-bank/list.png",                  label: "List",                 category: "dashboard" },
	],
	"national-commercial-bank": [
		{ id: "ncb1",  url: "/screenshots/national-commercial-bank/login.png",              label: "Login",           category: "auth" },
		{ id: "ncb2",  url: "/screenshots/national-commercial-bank/home.png",               label: "Home",            category: "dashboard" },
		{ id: "ncb3",  url: "/screenshots/national-commercial-bank/accounts.png",           label: "My Accounts",     category: "dashboard" },
		{ id: "ncb4",  url: "/screenshots/national-commercial-bank/accounts-2.png",         label: "My Accounts",     category: "dashboard" },
		{ id: "ncb5",  url: "/screenshots/national-commercial-bank/mailbox.png",            label: "Mailbox",         category: "dashboard" },
		{ id: "ncb6",  url: "/screenshots/national-commercial-bank/mailbox-2.png",          label: "Mailbox",         category: "dashboard" },
		{ id: "ncb7",  url: "/screenshots/national-commercial-bank/mailbox-3.png",          label: "Mailbox",         category: "dashboard" },
		{ id: "ncb8",  url: "/screenshots/national-commercial-bank/branches-atm.png",       label: "Branches & ATM",  category: "dashboard" },
		{ id: "ncb9",  url: "/screenshots/national-commercial-bank/currency-rates.png",     label: "Currency Rates",  category: "dashboard" },
		{ id: "ncb10", url: "/screenshots/national-commercial-bank/customer-service.png",   label: "Customer Service",category: "settings" },
		{ id: "ncb11", url: "/screenshots/national-commercial-bank/account-opening.png",    label: "Account Opening", category: "onboarding" },
		{ id: "ncb12", url: "/screenshots/national-commercial-bank/account-opening-2.png",  label: "Account Opening", category: "onboarding" },
		{ id: "ncb13", url: "/screenshots/national-commercial-bank/account-opening-3.png",  label: "Account Opening", category: "onboarding" },
		{ id: "ncb14", url: "/screenshots/national-commercial-bank/account-opening-4.png",  label: "Account Opening", category: "onboarding" },
		{ id: "ncb15", url: "/screenshots/national-commercial-bank/account-opening-5.png",  label: "Account Opening", category: "onboarding" },
		{ id: "ncb16", url: "/screenshots/national-commercial-bank/account-opening-6.png",  label: "Account Opening", category: "onboarding" },
		{ id: "ncb17", url: "/screenshots/national-commercial-bank/account-opening-7.png",  label: "Account Opening", category: "onboarding" },
		{ id: "ncb18", url: "/screenshots/national-commercial-bank/account-opening-8.png",  label: "Account Opening", category: "onboarding" },
		{ id: "ncb19", url: "/screenshots/national-commercial-bank/account-opening-9.png",  label: "Account Opening", category: "onboarding" },
	],
	"wahda-bank": [
		{ id: "w1",  url: "/screenshots/wahda-bank/home.png",                label: "Home",               category: "dashboard" },
		{ id: "w2",  url: "/screenshots/wahda-bank/analytics.png",           label: "Analytics",          category: "dashboard" },
		{ id: "w3",  url: "/screenshots/wahda-bank/cards.png",               label: "Cards",              category: "dashboard" },
		{ id: "w4",  url: "/screenshots/wahda-bank/card-store.png",          label: "Card Store",         category: "transaction" },
		{ id: "w5",  url: "/screenshots/wahda-bank/financing-services.png",  label: "Financing Services", category: "dashboard" },
		{ id: "w6",  url: "/screenshots/wahda-bank/qr-payment.png",          label: "QR Payment",         category: "transaction" },
		{ id: "w7",  url: "/screenshots/wahda-bank/profile.png",             label: "Profile",            category: "settings" },
		{ id: "w8",  url: "/screenshots/wahda-bank/verification.png",        label: "Verification",       category: "auth" },
		{ id: "w9",  url: "/screenshots/wahda-bank/account-statement.png",   label: "Account Statement",  category: "dashboard" },
		{ id: "w10", url: "/screenshots/wahda-bank/account-statement-2.png", label: "Account Statement",  category: "dashboard" },
		{ id: "w11", url: "/screenshots/wahda-bank/money-transfer.png",      label: "Money Transfer",     category: "transaction" },
		{ id: "w12", url: "/screenshots/wahda-bank/money-transfer-2.png",    label: "Money Transfer",     category: "transaction" },
		{ id: "w13", url: "/screenshots/wahda-bank/add-beneficiary.png",     label: "Add Beneficiary",    category: "transaction" },
	],
};
